import { CommonModule } from '@angular/common';
import { Component, Input, output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatRadioModule } from '@angular/material/radio';
import { client } from '../app.component';
import { solicit_feedback_for_given_question_and_response } from '../prompt-bedrock/prompt-bedrock.component';
import { Subject } from 'rxjs';

export enum FEEDBACK_SCORING_METHOD {
    A_SINGLE_FEEDBACK,
    JSON_FILE_OF_FEEDBACK,
};

@Component({
  selector: 'score-feedback-component',
  templateUrl: 'score-feedback.component.html',
  styleUrl: 'score-feedback.component.scss',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    MatRadioModule,
  ],
})
export class ScoreFeedbackComponent {
    Feedback_Scoring_Method = FEEDBACK_SCORING_METHOD;
    current_method = FEEDBACK_SCORING_METHOD.A_SINGLE_FEEDBACK;
    @Input({ required: false }) ai_generated_feedback: string = '';
    back_to_topic_page = output<void>();
    private _ai_feedback_is_loading_signal = new Subject<boolean>(); // KRISTIAN_TODO_NOW - Use this as a progress signnifier to how many feedback statements are generated.
    feedback_answer_key: string = '';
    feedback_score_is_loading: boolean = false;
    feedback_score: string | null = '';
    private _uploaded_json_content: any = null;
    public get uploaded_json_content(): any {
      return this._uploaded_json_content;
    }
    private _json_feedback_statements: any = null;
    public get json_feedback_statements(): any {
      return this._json_feedback_statements;
    }

    feedback_and_answer_key_are_empty() {
      return this.ai_generated_feedback?.length <= 0 || this.feedback_answer_key?.length <= 0;
    }

    async score_feedback(ai_generated_feedback: string, feedback_answer_key: string): Promise<void> {
        let prompt_with_feedback_pair_awaiting_score = "Given the AI-provided feedback of " + ai_generated_feedback +
          " and the feedback answer key of " + feedback_answer_key + ", please provide a score of 1 to 10 to measure" +
          "the semantic accuracy of the given AI-provided feedback based upon the given feedback answer key.";
        
        this.feedback_score_is_loading = true;

        const {data, errors} = await client.queries.tutorSwedish({
          prompt: prompt_with_feedback_pair_awaiting_score,
        });

        if (!errors) {
          // KRISTIAN_TODO_NOW - How to store the score in this component?  Store its details in a dialog that offers the user to save it in a file...
          // console.log (data);
          this.feedback_score = data; // KRISTIAN_TODO_NOW - Return this so I can reuse the method in score_feedback_generated_list.
          } else {
          console.log (errors);
        }
        this.feedback_score_is_loading = false;
    }

    on_json_file_uploaded (event: any): void {
      // KRISTIAN_NOTE - In theory, one can obtain A filepath from event.target.value, BUT it is a fakepath for security reasons.
      // The simplest way I found to read the contents of an uploaded file is to call readAsText with JavaScript's own FileReader
      // and parse the raw string back into JSON. 
      // https://dev.to/mayvid14/file-uploads-in-angular-10-or-javascript-in-general-4g9p
      const file_reader = new FileReader();
      file_reader.onload = (reader_event: any) => {
        this._uploaded_json_content = JSON.parse (reader_event?.target?.result);
      };
      file_reader.readAsText (event?.target?.files[0]);
    }

    async give_feedback_for_json_file (): Promise<void> {
      let json_feedback_statements = [];
      for (const ix in this._uploaded_json_content) {
        console.log (ix);
        const question = this._uploaded_json_content[ix]['question'];
        const response = this._uploaded_json_content[ix]['response'];
        // KRISTIAN_TODO_NOW - Better error handling...
        if (question?.length > 0 && response?.length > 0) {
          const feedback = await solicit_feedback_for_given_question_and_response (question, response, this._ai_feedback_is_loading_signal);
          console.log (feedback);
          json_feedback_statements.push (feedback);
        }
      }
      this._json_feedback_statements = json_feedback_statements;
    }

    async score_feedback_generated_list(): Promise<void> {
      // KRISTIAN_TODO_NOW - Given a series of feedback statements generated by the previous function
      // AND 
      // a "feedback answer key" list,
      // score ALL the feedback statements and a return a list.
      let scores = [];
      for (const ix in this._uploaded_json_content) {
        console.log (ix);
        // KRISTIAN_TODO_NOW - What if there's more ai feedback than feedback answers?  OR vice-versa??
        const ai_feedback = this._json_feedback_statements[ix];
        const feedback_answer = this._uploaded_json_content[ix]['feedback'];
        // const score = this.score_feedback (ai_feedback, feedback_answer); // KRISTIAN_TODO_NOW - prints out scores ok, but function returns void for now... 
        // console.log (score);
      }
    }

    redirect_user_to_topic_page(): void {
      this.back_to_topic_page.emit();
    }
}